const queryKeys = {
  teams: () => ["teams"],
  team: (teamId) => ["team", teamId],
  teamPlayers: (teamId) => ["teamPlayers", teamId],
  schedule: () => ["schedule"],
  weather: (lat, lon) => ["weather", lat, lon],
  messages: (teamId) => ["messages", teamId],
  currentUser: (token) => ["currentUser", token],
  events: (teamId) => ["events", teamId],
  event: (eventId) => ["event", eventId],
  attendance: (eventId, playerId) => ["attendance", eventId, playerId],
  announcements: (teamId) => ["announcements", teamId],
  documents: (teamId) => ["documents", teamId],
  playerNotes: (playerId) => ["playerNotes", playerId],
  products: (type) => ["products", type],
  registrations: (playerId) => ["registrations", playerId],
  registration: (id) => ["registration", id],
  activeWaiver: () => ["activeWaiver"],
  waiverSignatures: (playerId) => ["waiverSignatures", playerId],
  paymentHistory: (userId) => ["paymentHistory", userId],
  balance: (playerId) => ["balance", playerId],
  recruitingProfile: (playerId) => ["recruitingProfile", playerId],
  recruitingSearch: (criteria) => ["recruitingSearch", criteria],
  pendingCollegeCoachRequests: () => ["pendingCollegeCoachRequests"],
  performanceEntries: (playerId) => ["performanceEntries", playerId],
  performanceGoals: (playerId) => ["performanceGoals", playerId],
  analyticsDashboard: () => ["analyticsDashboard"],
  tournaments: () => ["tournaments"],
  tournament: (id) => ["tournament", id],
  hotelReservations: (tournamentId) => ["hotelReservations", tournamentId],
  pendingHotelReservations: () => ["pendingHotelReservations"],
  coachPayments: (coachUserId) => ["coachPayments", coachUserId],
  lessonSlots: (filters) => ["lessonSlots", filters],
};

export { queryKeys };
