import team18UGold from "../assets/team2.jpg";
import team18UPremier from "../assets/team18UPremier.jpg";

const baseUrl = import.meta.env.PROD
  ? "https://huskieshub-backend-891073803869.us-central1.run.app"
  : "http://localhost:8080";

const defaultImage = `${baseUrl}/images/default`; // your backend default route

const playersData = [
  {
    _id: 1,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Premier",
    banner: team18UPremier,
    players: [
      {
        _id: 101,
        name: "Antonella Sottile",
        jersey: 1,
        position: "P, CF",
        gradYear: 2026,
        highSchool: "Immaculate Heart Academy",
        GPA: 3.8,
        image: `${baseUrl}/images/as`, // ← backend
      },
      {
        _id: 102,
        name: "Ana Feliciano",
        jersey: 5,
        position: "",
        gradYear: 2027,
        highSchool: "Pompton Lakes High School",
        GPA: 3.79,
        image: defaultImage,
      },
      {
        _id: 103,
        name: "Sofia Rocha",
        jersey: 14,
        position: "OF",
        gradYear: 2026,
        highSchool: "Nutley High School",
        GPA: 3.4,
        image: `${baseUrl}/images/sr`,
      },
      {
        _id: 104,
        name: "Gabriella Brieva",
        jersey: 24,
        position: "C, 3B",
        gradYear: 2028,
        highSchool: "Wanaque High School",
        GPA: "",
        image: `${baseUrl}/images/gb`,
      },
      {
        _id: 105,
        name: "Ashley Witkowski",
        jersey: 2,
        position: "IF, OF",
        gradYear: 2027,
        highSchool: "Pascack Valley High School",
        GPA: 4.0,
        image: `${baseUrl}/images/aw`,
      },
      {
        _id: 106,
        name: "Emilia Kelley",
        jersey: 10,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Ridgewood High School",
        GPA: 3.5,
        image: `${baseUrl}/images/ek`,
      },
      {
        _id: 107,
        name: "Izzy Marut",
        jersey: 16,
        position: "OF",
        gradYear: 2028,
        highSchool: "Butler High School",
        GPA: 3.8,
        image: `${baseUrl}/images/im`,
      },
      {
        _id: 108,
        name: "Jordyn Struyk",
        jersey: 99,
        position: "OF, IF",
        gradYear: 2029,
        highSchool: "High School",
        GPA: "",
        image: `${baseUrl}/images/js`,
      },
      {
        _id: 109,
        name: "Lexi Feliciano",
        jersey: 4,
        position: "",
        gradYear: 2027,
        highSchool: "Pompton Lakes High School",
        GPA: 3.5,
        image: `${baseUrl}/images/lf`,
      },
      {
        _id: 110,
        name: "Kylee Bianchini",
        jersey: 13,
        position: "1B, 3B",
        gradYear: 2026,
        highSchool: "Wayne Valley High School",
        GPA: 3.3,
        image: `${baseUrl}/images/kb`,
      },
      {
        _id: 111,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF",
        gradYear: 2026,
        highSchool: "Fair Lawn High School",
        GPA: 3.8,
        image: `${baseUrl}/images/nd`,
      },
      {
        _id: 112,
        name: "Arianna Morran",
        jersey: 12,
        position: "P",
        gradYear: 2027,
        highSchool: "West Milford High School",
        GPA: 3.5,
        image: `${baseUrl}/images/am`,
      },
    ],
  },

  {
    _id: 2,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Gold",
    banner: team18UGold,
    players: [
      {
        _id: 201,
        name: "Lucy Sobel",
        jersey: "00",
        position: "P, Utility",
        gradYear: 2026,
        highSchool: "Ramsey High School",
        GPA: 4.1,
        isCommitted: true,
        committedCollege: "Middlebury College",
        image: `${baseUrl}/images/ls`,
      },
      {
        _id: 202,
        name: "Trinity Horn",
        jersey: 9,
        position: "RHP, OF",
        gradYear: 2027,
        highSchool: "Ramapo High School",
        GPA: 3.8,
        image: `${baseUrl}/images/th`,
      },
      {
        _id: 203,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF, 1B",
        gradYear: 2026,
        highSchool: "Fair Lawn High School",
        GPA: 3.8,
        image: `${baseUrl}/images/nd`,
      },
      {
        _id: 204,
        name: "Madelyn Saraceno",
        jersey: 22,
        position: "CF, Utility",
        gradYear: 2028,
        highSchool: "Ridgwood High School",
        GPA: 3.5,
        image: defaultImage,
      },
      {
        _id: 205,
        name: "Sophia Biroc",
        jersey: 3,
        position: "RHP, OF",
        gradYear: 2026,
        highSchool: "Wayne Valley High School",
        GPA: 3.75,
        isCommitted: true,
        committedCollege: "Roanoke College",
        image: `${baseUrl}/images/sb`,
      },
      {
        _id: 206,
        name: "Ava Conolly",
        jersey: 10,
        position: "C, 3B, 1B",
        gradYear: 2026,
        highSchool: "Wayne Hills High School",
        GPA: 3.7,
        isCommitted: true,
        committedCollege: "Washington College",
        image: `${baseUrl}/images/ac`,
      },
      {
        _id: 207,
        name: "Charlotte Feng",
        jersey: 19,
        position: "C, 2B, 3B",
        gradYear: 2026,
        highSchool: "Morris Tech High School",
        GPA: 4.68,
        isCommitted: true,
        committedCollege: "MIT",
        image: `${baseUrl}/images/cf`,
      },
      {
        _id: 208,
        name: "Ella Mchugh",
        jersey: 28,
        position: "SS, 2B, Utility",
        gradYear: 2027,
        highSchool: "Pearl River High School",
        GPA: 3.8,
        image: `${baseUrl}/images/em`,
      },
      {
        _id: 209,
        name: "Cali Dembowski",
        jersey: 7,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Pascack Valley High School",
        GPA: 4.2,
        image: `${baseUrl}/images/cd`,
      },
      {
        _id: 210,
        name: "Angie Franzese",
        jersey: 13,
        position: "MIF",
        gradYear: 2026,
        highSchool: "Pearl River High School",
        GPA: 3.2,
        isCommitted: true,
        committedCollege: "Albertus Magnus College",
        image: `${baseUrl}/images/af`,
      },
      {
        _id: 211,
        name: "Therese Adams",
        jersey: 21,
        position: "3B,MIF, OF",
        gradYear: 2026,
        highSchool: "Ramapo High School",
        GPA: 4.0,
        image: defaultImage,
      },
      {
        _id: 212,
        name: "Lily Kriz",
        jersey: 44,
        position: "C, 3B Utility",
        gradYear: 2026,
        highSchool: "Ramsey High School",
        GPA: 4.96,
        image: `${baseUrl}/images/lk`,
      },
    ],
  },
];
// coachesData.js
// Empire State Huskies — Coaches Directory

const coachesData = [
  {
    id: "A",
    name: "Allie Yoffee",
    role: "Head Coach",
    bio: `Allie Yoffee is the founder and head coach of the Empire State Huskies. 
With over a decade of coaching experience, she has led numerous teams to 
state and national championships. Her dedication to player development and 
passion for the game make her an invaluable asset to the Huskies organization.`,
    email: "alliey@gmail.com",
    phone: "201-410-0431",
    image: "allie.jpg", // Replace with your GridFS filename if needed
  },
  {
    id: "J",
    name: "Jessica Shulman",
    role: "Assistant Coach",
    bio: `Jessica Shulman brings a wealth of experience to the Huskies as an 
assistant coach. A former collegiate athlete, Jessica specializes in hitting 
mechanics and offensive strategy. Her hands-on approach and ability to connect 
with players help foster a positive and competitive team environment.`,
    email: "",
    phone: "",
    image: "jessica.jpg",
  },
  {
    id: "M",
    name: "Megan Wargo",
    role: "Pitching Coach",
    bio: `Megan Wargo is the Huskies' dedicated pitching coach, known for her 
technical expertise and personalized coaching style. With a background in 
collegiate softball, Megan focuses on developing pitchers' mechanics, mental 
toughness, and game strategy. Her commitment to each player's growth is evident 
in the Huskies' strong pitching performances.`,
    email: "",
    phone: "",
    image: "megan.jpg",
  },
];

export { baseUrl, coachesData, playersData };
