import team18UGold from "../assets/team2.jpg";
import team18UPremier from "../assets/team18UPremier.jpg";

const baseUrl = import.meta.env.PROD
  ? "https://huskieshub-backend-891073803869.us-central1.run.app"
  : "http://localhost:8080";

const defaultImage = `${baseUrl}/images/default`;

export const playersData = [
  {
    _id: 1,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Premier",
    banner: team18UPremier,
    players: [
      {
        _id: 101,
        name: "Antonella Sottile",
        jersey: 1,
        position: "P, CF",
        gradYear: 2026,
        highSchool: "Immaculate Heart Academy",
        GPA: 3.8,
        imageCode: "as",
      },
      {
        _id: 102,
        name: "Ana Feliciano",
        jersey: 5,
        gradYear: 2027,
        highSchool: "Pompton Lakes HS",
        GPA: 3.79,
        imageCode: null,
      },
      {
        _id: 103,
        name: "Sofia Rocha",
        jersey: 14,
        position: "OF",
        gradYear: 2026,
        highSchool: "Nutley HS",
        GPA: 3.4,
        imageCode: "sr",
      },
      {
        _id: 104,
        name: "Gabriella Brieva",
        jersey: 24,
        position: "C, 3B",
        gradYear: 2028,
        highSchool: "Wanaque HS",
        imageCode: "gb",
      },
      {
        _id: 105,
        name: "Ashley Witkowski",
        jersey: 2,
        position: "IF, OF",
        gradYear: 2027,
        highSchool: "Pascack Valley HS",
        GPA: 4.0,
        imageCode: "aw",
      },
      {
        _id: 106,
        name: "Emilia Kelley",
        jersey: 10,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Ridgewood HS",
        GPA: 3.5,
        imageCode: "ek",
      },
      {
        _id: 107,
        name: "Izzy Marut",
        jersey: 16,
        position: "OF",
        gradYear: 2028,
        highSchool: "Butler HS",
        GPA: 3.8,
        imageCode: "im",
      },
      {
        _id: 108,
        name: "Jordyn Struyk",
        jersey: 99,
        position: "OF, IF",
        gradYear: 2029,
        highSchool: "High School",
        imageCode: "js",
      },
      {
        _id: 109,
        name: "Lexi Feliciano",
        jersey: 4,
        gradYear: 2027,
        highSchool: "Pompton Lakes HS",
        GPA: 3.5,
        imageCode: "lf",
      },
      {
        _id: 110,
        name: "Kylee Bianchini",
        jersey: 13,
        position: "1B, 3B",
        gradYear: 2026,
        highSchool: "Wayne Valley HS",
        imageCode: "kb",
      },
      {
        _id: 111,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF",
        gradYear: 2026,
        highSchool: "Fair Lawn HS",
        imageCode: "nd",
      },
      {
        _id: 112,
        name: "Arianna Morran",
        jersey: 12,
        position: "P",
        gradYear: 2027,
        highSchool: "West Milford HS",
        imageCode: "am",
      },
    ],
  },

  {
    _id: 2,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Gold",
    banner: team18UGold,
    players: [
      {
        _id: 201,
        name: "Lucy Sobel",
        jersey: "00",
        position: "P, Utility",
        gradYear: 2026,
        highSchool: "Ramsey HS",
        imageCode: "ls",
      },
      {
        _id: 202,
        name: "Trinity Horn",
        jersey: 9,
        position: "RHP, OF",
        gradYear: 2027,
        highSchool: "Ramapo HS",
        imageCode: "th",
      },
      {
        _id: 203,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF, 1B",
        gradYear: 2026,
        highSchool: "Fair Lawn HS",
        imageCode: "nd",
      },
      {
        _id: 204,
        name: "Madelyn Saraceno",
        jersey: 22,
        position: "CF, Utility",
        gradYear: 2028,
        highSchool: "Ridgewood HS",
        imageCode: null,
      },
      {
        _id: 205,
        name: "Sophia Biroc",
        jersey: 3,
        position: "RHP, OF",
        gradYear: 2026,
        highSchool: "Wayne Valley HS",
        imageCode: "sb",
      },
      {
        _id: 206,
        name: "Ava Conolly",
        jersey: 10,
        position: "C, 3B, 1B",
        gradYear: 2026,
        highSchool: "Wayne Hills HS",
        imageCode: "ac",
      },
      {
        _id: 207,
        name: "Charlotte Feng",
        jersey: 19,
        position: "C, 2B, 3B",
        gradYear: 2026,
        highSchool: "Morris Tech HS",
        imageCode: "cf",
      },
      {
        _id: 208,
        name: "Ella Mchugh",
        jersey: 28,
        position: "SS, 2B",
        gradYear: 2027,
        highSchool: "Pearl River HS",
        GPA: 3.8,
        imageCode: "em",
      },
      {
        _id: 209,
        name: "Cali Dembowski",
        jersey: 7,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Pascack Valley HS",
        GPA: 4.2,
        imageCode: "cd",
      },
      {
        _id: 210,
        name: "Angie Franzese",
        jersey: 13,
        position: "MIF",
        gradYear: 2026,
        highSchool: "Pearl River HS",
        GPA: 3.2,
        imageCode: "af",
      },
      {
        _id: 211,
        name: "Therese Adams",
        jersey: 21,
        position: "3B, MIF, OF",
        gradYear: 2026,
        highSchool: "Ramapo HS",
        imageCode: null,
      },
      {
        _id: 212,
        name: "Lily Kriz",
        jersey: 44,
        position: "C, 3B",
        gradYear: 2026,
        highSchool: "Ramsey HS",
        imageCode: "lk",
      },
    ],
  },
];

export { baseUrl };
