import team18UGold from "../assets/team2.jpg";
import team18UPremier from "../assets/team18UPremier.jpg";

const baseUrl = import.meta.env.PROD
  ? "https://api.eshuskiesyoffee.com" ||
    "https://huskieshub-backend-891073803869.us-central1.run.app"
  : "http://localhost:8080";

// GridFS default image file
const defaultImage = "default.avif";

// -------------------
// PLAYERS DATA
// -------------------
const playersData = [
  {
    _id: 1,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Premier",
    banner: team18UPremier,
    players: [
      {
        _id: 101,
        name: "Antonella Sottile",
        jersey: 1,
        position: "P, CF",
        gradYear: 2026,
        highSchool: "Immaculate Heart Academy",
        GPA: 3.8,
        image: "as.jpg",
      },
      {
        _id: 102,
        name: "Ana Feliciano",
        jersey: 5,
        position: "",
        gradYear: 2027,
        highSchool: "Pompton Lakes High School",
        GPA: 3.79,
        image: defaultImage,
      },
      {
        _id: 103,
        name: "Sofia Rocha",
        jersey: 14,
        position: "OF",
        gradYear: 2026,
        highSchool: "Nutley High School",
        GPA: 3.4,
        image: "sr.jpg",
      },
      {
        _id: 104,
        name: "Gabriella Brieva",
        jersey: 24,
        position: "C, 3B",
        gradYear: 2028,
        highSchool: "Wanaque High School",
        GPA: "",
        image: "gb.jpg",
      },
      {
        _id: 105,
        name: "Ashley Witkowski",
        jersey: 2,
        position: "IF, OF",
        gradYear: 2027,
        highSchool: "Pascack Valley High School",
        GPA: 4.0,
        image: "aw.jpg",
      },
      {
        _id: 106,
        name: "Emilia Kelley",
        jersey: 10,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Ridgewood High School",
        GPA: 3.5,
        image: "ek.jpg",
      },
      {
        _id: 107,
        name: "Izzy Marut",
        jersey: 16,
        position: "OF",
        gradYear: 2028,
        highSchool: "Butler High School",
        GPA: 3.8,
        image: "im.jpg",
      },
      {
        _id: 108,
        name: "Jordyn Struyk",
        jersey: 99,
        position: "OF, IF",
        gradYear: 2029,
        highSchool: "High School",
        GPA: "",
        image: "js.jpg",
      },
      {
        _id: 109,
        name: "Lexi Feliciano",
        jersey: 4,
        position: "",
        gradYear: 2027,
        highSchool: "Pompton Lakes High School",
        GPA: 3.5,
        image: "lf.jpg",
      },
      {
        _id: 110,
        name: "Kylee Bianchini",
        jersey: 13,
        position: "1B, 3B",
        gradYear: 2026,
        highSchool: "Wayne Valley High School",
        GPA: 3.3,
        image: "kb.jpg",
      },
      {
        _id: 111,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF",
        gradYear: 2026,
        highSchool: "Fair Lawn High School",
        GPA: 3.8,
        image: "nd.jpg",
      },
      {
        _id: 112,
        name: "Arianna Morran",
        jersey: 12,
        position: "P",
        gradYear: 2027,
        highSchool: "West Milford High School",
        GPA: 3.5,
        image: "am.jpg",
      },
    ],
  },

  // -------------------
  // 18U GOLD
  // -------------------
  {
    _id: 2,
    name: "Empire State Huskies Yoffee",
    ageGroup: "18U Gold",
    banner: team18UGold,
    players: [
      {
        _id: 201,
        name: "Lucy Sobel",
        jersey: "00",
        position: "P, Utility",
        gradYear: 2026,
        highSchool: "Ramsey High School",
        GPA: 4.1,
        isCommitted: true,
        committedCollege: "Middlebury College",
        image: "ls.jpg",
      },
      {
        _id: 202,
        name: "Trinity Horn",
        jersey: 9,
        position: "RHP, OF",
        gradYear: 2027,
        highSchool: "Ramapo High School",
        GPA: 3.8,
        image: "th.jpg",
      },
      {
        _id: 203,
        name: "Natalie Davis",
        jersey: 17,
        position: "OF, 1B",
        gradYear: 2026,
        highSchool: "Fair Lawn High School",
        GPA: 3.8,
        image: "nd.jpg",
      },
      {
        _id: 204,
        name: "Madelyn Saraceno",
        jersey: 22,
        position: "CF, Utility",
        gradYear: 2028,
        highSchool: "Ridgwood High School",
        GPA: 3.5,
        image: defaultImage,
      },
      {
        _id: 205,
        name: "Sophia Biroc",
        jersey: 3,
        position: "RHP, OF",
        gradYear: 2026,
        highSchool: "Wayne Valley High School",
        GPA: 3.75,
        isCommitted: true,
        committedCollege: "Roanoke College",
        image: "sb.jpg",
      },
      {
        _id: 206,
        name: "Ava Conolly",
        jersey: 10,
        position: "C, 3B, 1B",
        gradYear: 2026,
        highSchool: "Wayne Hills High School",
        GPA: 3.7,
        isCommitted: true,
        committedCollege: "Washington College",
        image: "ac.jpg",
      },
      {
        _id: 207,
        name: "Charlotte Feng",
        jersey: 19,
        position: "C, 2B, 3B",
        gradYear: 2026,
        highSchool: "Morris Tech High School",
        GPA: 4.68,
        isCommitted: true,
        committedCollege: "MIT",
        image: "cf.jpg",
      },
      {
        _id: 208,
        name: "Ella Mchugh",
        jersey: 28,
        position: "SS, 2B, Utility",
        gradYear: 2027,
        highSchool: "Pearl River High School",
        GPA: 3.8,
        image: "em.jpg",
      },
      {
        _id: 209,
        name: "Cali Dembowski",
        jersey: 7,
        position: "C, OF",
        gradYear: 2026,
        highSchool: "Pascack Valley High School",
        GPA: 4.2,
        image: "cd.jpg",
      },
      {
        _id: 210,
        name: "Angie Franzese",
        jersey: 13,
        position: "MIF",
        gradYear: 2026,
        highSchool: "Pearl River High School",
        GPA: 3.2,
        isCommitted: true,
        committedCollege: "Albertus Magnus College",
        image: "af.jpg",
      },
      {
        _id: 211,
        name: "Therese Adams",
        jersey: 21,
        position: "3B, MIF, OF",
        gradYear: 2026,
        highSchool: "Ramapo High School",
        GPA: 4.0,
        image: defaultImage,
      },
      {
        _id: 212,
        name: "Lily Kriz",
        jersey: 44,
        position: "C, 3B Utility",
        gradYear: 2026,
        highSchool: "Ramsey High School",
        GPA: 4.96,
        image: "lk.jpg",
      },
    ],
  },
];

// -------------------
// COACHES
// -------------------
const coachesData = [
  {
    id: "A",
    name: "Allie Yoffee",
    role: "Head Coach",
    bio: `Allie Yoffee is the founder...`,
    email: "alliey@gmail.com",
    phone: "201-410-0431",
    image: defaultImage,
  },
  {
    id: "J",
    name: "Jessica Shulman",
    role: "Assistant Coach",
    bio: `Jessica Shulman brings a wealth...`,
    email: "",
    phone: "",
    image: defaultImage,
  },
  {
    id: "M",
    name: "Megan Wargo",
    role: "Pitching Coach",
    bio: `Megan Wargo is the Huskies' dedicated pitching coach...`,
    email: "",
    phone: "",
    image: defaultImage,
  },
];

export { baseUrl, coachesData, playersData };
